name: time_tuner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  credential_manager: ^1.0.2
  firebase_auth: ^5.1.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  sign_in_button: ^3.2.0
  terminal_color_parser: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - images/


